apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.basename }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 6443
      targetPort: 6443
  selector:
    app: {{ .Values.basename }}-server
