# kubectl exec -n kubestellar $(kubectl get pod -n kubestellar --selector=app=kubestellar-client -o jsonpath={.items[0].metadata.name}) -- kubectl ws .
# kubectl exec -n kubestellar $(kubectl get pod -n kubestellar --selector=app=kubestellar-server -o jsonpath={.items[0].metadata.name}) -- cat /.kcp/admin.kubeconfig
# kubectl cp  -n kubestellar $(kubectl get pod -n kubestellar --selector=app=kubestellar-server -o jsonpath={.items[0].metadata.name}):/.kcp/admin.kubeconfig ./admin.kubeconfig
# kubectl port-forward -n kubestellar pod/$(kubectl get pod -n kubestellar --selector=app=kubestellar-server -o jsonpath={.items[0].metadata.name}) 6443:6443 --address='0.0.0.0'
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubestellar
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubestellar-pvc
  namespace: kubestellar
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubestellar-server
  namespace: kubestellar
spec:
  selector:
    matchLabels:
      app: kubestellar-server
  replicas: 1
  template:
    metadata:
      labels:
        app: kubestellar-server
    spec:
      volumes:
      - name: kubestellar-pv
        persistentVolumeClaim:
          claimName: kubestellar-pvc
      containers:
      - name: kubestellar-server
        image: quay.io/kubestellar/kubestellar:stable
        volumeMounts:
        - name: kubestellar-pv
          mountPath: "/.kcp"
          readOnly: false
---
kind: Service
apiVersion: v1
metadata:
  name: kubestellar-service
  namespace: kubestellar
spec:
  selector:
    app: kubestellar-server
  ports:
    - port: 6443 # Default port for image
      targetPort: 6443
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kubestellar-client
#   namespace: kubestellar
# spec:
#   selector:
#     matchLabels:
#       app: kubestellar-client
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: kubestellar-client
#     spec:
#       volumes:
#       - name: kubestellar-pv
#         persistentVolumeClaim:
#           claimName: kubestellar-pvc
#       containers:
#       - name: kubestellar-server
#         image: quay.io/kubestellar/kubestellar:stable
#         volumeMounts:
#         - name: kubestellar-pv
#           mountPath: "/.kcp"
#           readOnly: false
#         command: [ "/bin/bash" ]
#         args:
#           - -c
#           - >-
#               echo Sleeping
#               && sleep 100000